version: '3.8'
services:
  frontend:
    image: weichongdevelops/fulcrum-frontend:1.0
    ports:
      - "80:80"
    restart: "no"
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    image: weichongdevelops/fulcrum-backend:1.0
    ports:
      - "8080:8080"
    restart: "no"
    networks:
      - app-network
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - SUPABASE_KEY=${SUPABASE_KEY}
      - DISPLAY=host.docker.internal:0
networks:
  app-network:
    driver: bridge

