services:
  frontend:
    image: weichongdevelops/fulcrum-frontend:1.0
    build:
      context: "./Fulcrum React"
      args:
        VITE_SUPABASE_KEY: ${SUPABASE_KEY}
    ports:
      - "80:3001"
    restart: "on-failure"
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    image: weichongdevelops/fulcrum-backend:1.0
    ports:
      - "8080:8080"
    restart: "on-failure"
    networks:
      - app-network
    environment:
      - SUPABASE_KEY=${SUPABASE_KEY}
networks:
  app-network:
    driver: bridge

