
export interface ExpenseItemEntity {
    expenseId: string
    userId: string
    categoryId: string
    amount: number
    timestamp: Date
}

export const tempStartExpenseList: ExpenseItemEntity[] = [
    {
        expenseId: "", // this will be generated by the server
        userId: "root",
        categoryId: "1",
        amount: 20.55,
        timestamp: new Date()
    },
    {
        expenseId: "", // this will be generated by the server
        userId: "root",
        categoryId: "2",
        amount: 50.65,
        timestamp: new Date()
    },
    {
        expenseId: "", // this will be generated by the server
        userId: "root",
        categoryId: "3",
        amount: 120.50,
        timestamp: new Date()
    },
]